### ISSUE TITLE
Avoid diagonal path

### ISSUE THREAD

**Issue by mrjeanjean** [RonenNess/Unity-2d-pathfinding#1]
Thanks for your transcription. It's easier to implement with this way.
Just a question. Do you know a way to avoid diagonal path between two tiles (I just need left <->right, bottom<->up behavior)? I'll try to implement it as an option. But if you think about a way to proceed... :)
Thanks in advance.

**Comment by RonenNess** [comment]
Hi mOveoStudio,

You should change this function:
https://github.com/RonenNess/Unity-2d-pathfinding/blob/master/PathFinding/Grid.cs#L59

And make it return only the top / bottom / left / right neighbors.
I think it should do the trick, please let me know if its working or not so I can close the ticket.

Thanks! :)

**Comment by mrjeanjean** [comment]
Thanks Ronen. That's exactly the point! That calls the Von Neumann neighborhood (Wikipedia said ;)).
Thanks again.
